/**
 * <p>The controller package handles the actions generated by the view, calls the model and shows the results
 * back to the view (MVC pattern).</p>
 * <p>Copyright (c) <a href="https://reflection.uniovi.es/ortin/">Francisco Ortin</a>.</p>
 * <p>MIT license.</p>
 * @author Francisco Ortin
 */
package introspector.controller;
